# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-25 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_football_api', '0002_auto_20180825_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(),
        ),
    ]
